import 'dotenv/config';
import { prisma } from '../src/lib/prisma';
import { TicketStatus, TicketCategory } from '../src/generated/prisma/client';

// Spread dates over the past 6 months
function daysAgo(days: number): Date {
  const d = new Date();
  d.setDate(d.getDate() - days);
  return d;
}

const tickets: {
  subject: string;
  body: string;
  customerName: string;
  customerEmail: string;
  status: TicketStatus;
  category: TicketCategory | null;
  createdAt: Date;
}[] = [
  // REFUND_REQUEST — OPEN
  {
    subject: 'Refund request for order #84721',
    body: 'I ordered a laptop stand last week but it never arrived. I would like a full refund.',
    customerName: 'Alice Johnson',
    customerEmail: 'alice.johnson@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.REFUND_REQUEST,
    createdAt: daysAgo(2),
  },
  {
    subject: 'Double charged on November invoice',
    body: 'My credit card was charged twice for the same invoice. Please refund the duplicate charge immediately.',
    customerName: 'Bob Martinez',
    customerEmail: 'bob.martinez@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.REFUND_REQUEST,
    createdAt: daysAgo(3),
  },
  {
    subject: 'Wrong item shipped — requesting refund',
    body: 'I ordered a blue wireless keyboard (SKU KB-300B) but received a red wired one. I want a refund, not a replacement.',
    customerName: 'Carol White',
    customerEmail: 'carol.white@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.REFUND_REQUEST,
    createdAt: daysAgo(5),
  },
  {
    subject: 'Subscription cancelled but still charged',
    body: 'I cancelled my Pro subscription on the 1st but was charged again on the 15th. Please refund this month\'s fee.',
    customerName: 'David Lee',
    customerEmail: 'david.lee@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.REFUND_REQUEST,
    createdAt: daysAgo(1),
  },
  {
    subject: 'Product arrived damaged',
    body: 'The monitor I ordered arrived with a cracked screen. I have attached photos. Please process a full refund.',
    customerName: 'Eva Chen',
    customerEmail: 'eva.chen@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.REFUND_REQUEST,
    createdAt: daysAgo(4),
  },

  // REFUND_REQUEST — RESOLVED
  {
    subject: 'Refund for accidental purchase',
    body: 'My 8-year-old accidentally purchased the annual plan. We only need the monthly. Can I get a refund?',
    customerName: 'Frank Nguyen',
    customerEmail: 'frank.nguyen@example.com',
    status: TicketStatus.RESOLVED,
    category: TicketCategory.REFUND_REQUEST,
    createdAt: daysAgo(15),
  },
  {
    subject: 'Charged after free trial ended unexpectedly',
    body: 'I was not notified before my trial converted to a paid plan. I never intended to subscribe. Please refund.',
    customerName: 'Grace Kim',
    customerEmail: 'grace.kim@example.com',
    status: TicketStatus.RESOLVED,
    category: TicketCategory.REFUND_REQUEST,
    createdAt: daysAgo(20),
  },
  {
    subject: 'Duplicate order placed by mistake',
    body: 'I accidentally placed the same order twice within 30 seconds. Please cancel and refund one of them.',
    customerName: 'Henry Park',
    customerEmail: 'henry.park@example.com',
    status: TicketStatus.RESOLVED,
    category: TicketCategory.REFUND_REQUEST,
    createdAt: daysAgo(25),
  },
  {
    subject: 'Refund for unused annual licence',
    body: 'We purchased 20 seats but only ended up using 12. Can we get a partial refund for the 8 unused seats?',
    customerName: 'Irene Torres',
    customerEmail: 'irene.torres@example.com',
    status: TicketStatus.RESOLVED,
    category: TicketCategory.REFUND_REQUEST,
    createdAt: daysAgo(30),
  },

  // REFUND_REQUEST — CLOSED
  {
    subject: 'Service outage refund request',
    body: 'Your platform was down for 6 hours last Thursday during a critical demo. I expect compensation.',
    customerName: 'James Brown',
    customerEmail: 'james.brown@example.com',
    status: TicketStatus.CLOSED,
    category: TicketCategory.REFUND_REQUEST,
    createdAt: daysAgo(45),
  },
  {
    subject: 'Refund for downgraded plan',
    body: 'I downgraded from Enterprise to Starter mid-cycle and expected a prorated refund. Nothing was credited.',
    customerName: 'Karen Wilson',
    customerEmail: 'karen.wilson@example.com',
    status: TicketStatus.CLOSED,
    category: TicketCategory.REFUND_REQUEST,
    createdAt: daysAgo(60),
  },

  // TECHNICAL_QUESTION — OPEN
  {
    subject: 'Cannot log in — says account does not exist',
    body: 'I\'ve been a customer for 2 years but today the login page says my email is not registered. I didn\'t delete my account.',
    customerName: 'Liam Garcia',
    customerEmail: 'liam.garcia@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(0),
  },
  {
    subject: 'Two-factor authentication codes not arriving',
    body: 'SMS codes for 2FA stopped arriving 3 days ago. I\'ve tried a different phone number but still nothing.',
    customerName: 'Mia Robinson',
    customerEmail: 'mia.robinson@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(1),
  },
  {
    subject: 'API returning 401 with valid token',
    body: 'Our integration has started receiving 401 Unauthorized on every request despite the token being valid and not expired.',
    customerName: 'Noah Clark',
    customerEmail: 'noah.clark@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(2),
  },
  {
    subject: 'CSV export is empty',
    body: 'When I export my data to CSV the file downloads but contains only headers and no rows. This worked fine last week.',
    customerName: 'Olivia Lewis',
    customerEmail: 'olivia.lewis@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(3),
  },
  {
    subject: 'Webhook not firing on order completion',
    body: 'Our fulfillment webhook stopped triggering. We\'ve verified the endpoint is live and the URL is correct in settings.',
    customerName: 'Paul Walker',
    customerEmail: 'paul.walker@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(4),
  },
  {
    subject: 'Mobile app crashes on iOS 18.2',
    body: 'After updating to iOS 18.2 the app crashes immediately on launch. Reinstalling does not fix it.',
    customerName: 'Quinn Adams',
    customerEmail: 'quinn.adams@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(1),
  },
  {
    subject: 'Email notifications not sending',
    body: 'We turned on email alerts for new orders but no emails are being received. Checked spam folder — nothing there either.',
    customerName: 'Rachel Scott',
    customerEmail: 'rachel.scott@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(6),
  },
  {
    subject: 'Dashboard charts not loading',
    body: 'The analytics charts on the dashboard show a spinning loader indefinitely. The rest of the page loads fine.',
    customerName: 'Sam Turner',
    customerEmail: 'sam.turner@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(5),
  },
  {
    subject: 'SSO login redirects to blank page',
    body: 'After setting up SSO with Okta, users are redirected to a blank white page instead of the app.',
    customerName: 'Tina Harris',
    customerEmail: 'tina.harris@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(2),
  },
  {
    subject: 'Search results are incorrect after recent update',
    body: 'Since last Tuesday\'s update, searching for customers by email returns completely unrelated results.',
    customerName: 'Uma Patel',
    customerEmail: 'uma.patel@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(7),
  },

  // TECHNICAL_QUESTION — RESOLVED
  {
    subject: 'Password reset email not arriving',
    body: 'I clicked "Forgot password" but no email arrived. I\'ve checked spam and the address is correct.',
    customerName: 'Victor Hughes',
    customerEmail: 'victor.hughes@example.com',
    status: TicketStatus.RESOLVED,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(12),
  },
  {
    subject: 'Rate limit hit on free plan unexpectedly',
    body: 'We\'re on the Business plan but getting 429 errors. Our usage dashboard shows we\'re under the limit.',
    customerName: 'Wendy Price',
    customerEmail: 'wendy.price@example.com',
    status: TicketStatus.RESOLVED,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(14),
  },
  {
    subject: 'Zapier integration stopped working',
    body: 'Our Zap was working fine for months but stopped triggering yesterday. No changes were made on our end.',
    customerName: 'Xavier Reed',
    customerEmail: 'xavier.reed@example.com',
    status: TicketStatus.RESOLVED,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(18),
  },
  {
    subject: 'File upload fails for files over 5 MB',
    body: 'Uploading attachments works for small files but anything over 5 MB gives an error: "Upload failed — please try again".',
    customerName: 'Yara Cooper',
    customerEmail: 'yara.cooper@example.com',
    status: TicketStatus.RESOLVED,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(22),
  },
  {
    subject: 'Custom domain setup not working',
    body: 'I\'ve added the CNAME records as instructed but my custom domain still shows a 404 after 48 hours.',
    customerName: 'Zoe Bailey',
    customerEmail: 'zoe.bailey@example.com',
    status: TicketStatus.RESOLVED,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(28),
  },
  {
    subject: 'Dark mode is broken on Firefox',
    body: 'When dark mode is enabled in Firefox v131, the text becomes invisible against the background. Works fine in Chrome.',
    customerName: 'Aaron Foster',
    customerEmail: 'aaron.foster@example.com',
    status: TicketStatus.RESOLVED,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(35),
  },

  // TECHNICAL_QUESTION — CLOSED
  {
    subject: 'Bulk import rejecting valid CSV format',
    body: 'The bulk user import rejects my CSV with "invalid format" even though I\'m using the provided template.',
    customerName: 'Beth Coleman',
    customerEmail: 'beth.coleman@example.com',
    status: TicketStatus.CLOSED,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(50),
  },
  {
    subject: 'Time zone shows wrong time in reports',
    body: 'All report timestamps are off by 5 hours. My account time zone is set correctly to EST.',
    customerName: 'Chris Jordan',
    customerEmail: 'chris.jordan@example.com',
    status: TicketStatus.CLOSED,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(55),
  },
  {
    subject: 'Print layout is broken on A4 paper',
    body: 'The invoice print layout cuts off the right column when printing to A4. It was fine before your last update.',
    customerName: 'Dana Long',
    customerEmail: 'dana.long@example.com',
    status: TicketStatus.CLOSED,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(65),
  },
  {
    subject: 'Keyboard shortcuts stopped working',
    body: 'After the Chrome extension updated, all keyboard shortcuts in the web app stopped responding.',
    customerName: 'Eli Patterson',
    customerEmail: 'eli.patterson@example.com',
    status: TicketStatus.CLOSED,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(80),
  },
  {
    subject: 'Push notifications not received on Android',
    body: 'Android users in our team have not been receiving push notifications for the past two weeks.',
    customerName: 'Faye Hughes',
    customerEmail: 'faye.hughes@example.com',
    status: TicketStatus.CLOSED,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(90),
  },

  // GENERAL_QUESTION — OPEN
  {
    subject: 'What are your support hours?',
    body: 'We are based in Sydney, Australia. What time zone are your support agents in and when can we reach them?',
    customerName: 'George Allen',
    customerEmail: 'george.allen@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.GENERAL_QUESTION,
    createdAt: daysAgo(0),
  },
  {
    subject: 'Do you offer a nonprofit discount?',
    body: 'We are a registered nonprofit. I saw you offer discounts on your pricing page but couldn\'t find details.',
    customerName: 'Hannah Young',
    customerEmail: 'hannah.young@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.GENERAL_QUESTION,
    createdAt: daysAgo(1),
  },
  {
    subject: 'Can I have multiple admins on one account?',
    body: 'We want to give admin access to three people on our team. Is that included in the Business plan or is there an extra cost?',
    customerName: 'Ivan King',
    customerEmail: 'ivan.king@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.GENERAL_QUESTION,
    createdAt: daysAgo(2),
  },
  {
    subject: 'How long is data retained after cancellation?',
    body: 'If we cancel our subscription, how long will our data be available for export before it is deleted?',
    customerName: 'Julia Wright',
    customerEmail: 'julia.wright@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.GENERAL_QUESTION,
    createdAt: daysAgo(3),
  },
  {
    subject: 'Is there a desktop app for Windows?',
    body: 'We\'ve been using the web app but our team prefers a native desktop experience. Is a Windows app on the roadmap?',
    customerName: 'Kevin Scott',
    customerEmail: 'kevin.scott@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.GENERAL_QUESTION,
    createdAt: daysAgo(4),
  },
  {
    subject: 'GDPR data processing agreement request',
    body: 'Our legal team requires a signed DPA before we can use your service. Can you send one?',
    customerName: 'Laura Green',
    customerEmail: 'laura.green@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.GENERAL_QUESTION,
    createdAt: daysAgo(5),
  },
  {
    subject: 'Can we pay by bank transfer instead of card?',
    body: 'Our finance department does not allow recurring credit card charges. Is invoicing via bank transfer available?',
    customerName: 'Marcus Baker',
    customerEmail: 'marcus.baker@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.GENERAL_QUESTION,
    createdAt: daysAgo(6),
  },
  {
    subject: 'Requesting a call with an account manager',
    body: 'We are evaluating your Enterprise plan for our organisation of 200+ employees. Can we schedule a demo call?',
    customerName: 'Nancy Hall',
    customerEmail: 'nancy.hall@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.GENERAL_QUESTION,
    createdAt: daysAgo(2),
  },

  // GENERAL_QUESTION — RESOLVED
  {
    subject: 'How do I transfer ownership of an account?',
    body: 'The original account owner has left the company. How do we transfer ownership to our new team lead?',
    customerName: 'Oscar Rivera',
    customerEmail: 'oscar.rivera@example.com',
    status: TicketStatus.RESOLVED,
    category: TicketCategory.GENERAL_QUESTION,
    createdAt: daysAgo(10),
  },
  {
    subject: 'Do you support PayPal for payments?',
    body: 'I\'d like to use PayPal for my subscription payments instead of a credit card. Is this possible?',
    customerName: 'Penelope Cox',
    customerEmail: 'penelope.cox@example.com',
    status: TicketStatus.RESOLVED,
    category: TicketCategory.GENERAL_QUESTION,
    createdAt: daysAgo(16),
  },
  {
    subject: 'Where can I find my invoices?',
    body: 'I need to download my invoices for the past 12 months for accounting purposes. I can\'t find them in the settings.',
    customerName: 'Quincy Morris',
    customerEmail: 'quincy.morris@example.com',
    status: TicketStatus.RESOLVED,
    category: TicketCategory.GENERAL_QUESTION,
    createdAt: daysAgo(20),
  },
  {
    subject: 'How do I add a team member?',
    body: 'I\'m the account owner and want to invite a colleague. I can\'t find the invite button in the team settings.',
    customerName: 'Rosa Rogers',
    customerEmail: 'rosa.rogers@example.com',
    status: TicketStatus.RESOLVED,
    category: TicketCategory.GENERAL_QUESTION,
    createdAt: daysAgo(24),
  },
  {
    subject: 'What happens if I exceed my plan limits?',
    body: 'I\'m approaching the 10,000 record limit on the Starter plan. Will access be cut off or will I be auto-upgraded?',
    customerName: 'Steve Peterson',
    customerEmail: 'steve.peterson@example.com',
    status: TicketStatus.RESOLVED,
    category: TicketCategory.GENERAL_QUESTION,
    createdAt: daysAgo(32),
  },

  // GENERAL_QUESTION — CLOSED
  {
    subject: 'Is there a free plan available?',
    body: 'I am a freelancer just starting out. Do you offer a free tier or a trial period without requiring a credit card?',
    customerName: 'Teresa Reed',
    customerEmail: 'teresa.reed@example.com',
    status: TicketStatus.CLOSED,
    category: TicketCategory.GENERAL_QUESTION,
    createdAt: daysAgo(40),
  },
  {
    subject: 'Do you have a status page?',
    body: 'I want to subscribe to uptime notifications. Do you publish a public status page for incidents?',
    customerName: 'Ulysses Watson',
    customerEmail: 'ulysses.watson@example.com',
    status: TicketStatus.CLOSED,
    category: TicketCategory.GENERAL_QUESTION,
    createdAt: daysAgo(50),
  },
  {
    subject: 'Requesting a VAT invoice',
    body: 'The PDF invoices I download do not include our company VAT number. How do I add it to future invoices?',
    customerName: 'Vera Brooks',
    customerEmail: 'vera.brooks@example.com',
    status: TicketStatus.CLOSED,
    category: TicketCategory.GENERAL_QUESTION,
    createdAt: daysAgo(70),
  },
  {
    subject: 'Are you SOC 2 certified?',
    body: 'Our security team requires SOC 2 Type II certification before approving vendor tools. Do you have this?',
    customerName: 'Walter Gray',
    customerEmail: 'walter.gray@example.com',
    status: TicketStatus.CLOSED,
    category: TicketCategory.GENERAL_QUESTION,
    createdAt: daysAgo(85),
  },

  // NULL CATEGORY — OPEN
  {
    subject: 'My account was suspended without notice',
    body: 'I received no warning email and my account is now showing as suspended. I have not violated any terms.',
    customerName: 'Xena Bryant',
    customerEmail: 'xena.bryant@example.com',
    status: TicketStatus.OPEN,
    category: null,
    createdAt: daysAgo(0),
  },
  {
    subject: 'Team members cannot see shared projects',
    body: 'I shared three projects with my team but only I can see them. Everyone else gets a "not found" error.',
    customerName: 'Yale Carter',
    customerEmail: 'yale.carter@example.com',
    status: TicketStatus.OPEN,
    category: null,
    createdAt: daysAgo(1),
  },
  {
    subject: 'Billing address wrong on all invoices',
    body: 'My billing address was updated 3 months ago but old invoices still show the previous address. This is a compliance issue.',
    customerName: 'Zara Collins',
    customerEmail: 'zara.collins@example.com',
    status: TicketStatus.OPEN,
    category: null,
    createdAt: daysAgo(3),
  },
  {
    subject: 'Theme customisation not saving',
    body: 'I update the brand colours and click Save, the page confirms success, but when I reload everything reverts to default.',
    customerName: 'Adam Dixon',
    customerEmail: 'adam.dixon@example.com',
    status: TicketStatus.OPEN,
    category: null,
    createdAt: daysAgo(5),
  },
  {
    subject: 'Report shows data from wrong date range',
    body: 'The monthly report for October is showing August data. I\'ve cleared the cache and tried a different browser.',
    customerName: 'Bella Edwards',
    customerEmail: 'bella.edwards@example.com',
    status: TicketStatus.OPEN,
    category: null,
    createdAt: daysAgo(7),
  },
  {
    subject: 'New employee cannot access assigned tasks',
    body: 'I added a new team member and assigned them several tasks but they see an empty workspace when they log in.',
    customerName: 'Carl Fleming',
    customerEmail: 'carl.fleming@example.com',
    status: TicketStatus.OPEN,
    category: null,
    createdAt: daysAgo(2),
  },
  {
    subject: 'Language changed to German automatically',
    body: 'The interface switched to German overnight. My locale is set to English (UK) and I haven\'t changed anything.',
    customerName: 'Diana Gibson',
    customerEmail: 'diana.gibson@example.com',
    status: TicketStatus.OPEN,
    category: null,
    createdAt: daysAgo(4),
  },
  {
    subject: 'Cannot delete old team members from account',
    body: 'Three former employees still show up in my team list. The delete button is greyed out for all of them.',
    customerName: 'Edward Hamilton',
    customerEmail: 'edward.hamilton@example.com',
    status: TicketStatus.OPEN,
    category: null,
    createdAt: daysAgo(6),
  },
  {
    subject: 'Audit log missing entries from last month',
    body: 'Our compliance team noticed the audit log for October has a 4-day gap with no entries. This is critical for us.',
    customerName: 'Fiona Irving',
    customerEmail: 'fiona.irving@example.com',
    status: TicketStatus.OPEN,
    category: null,
    createdAt: daysAgo(8),
  },
  {
    subject: 'Profile photo not updating',
    body: 'I\'ve tried uploading a new profile photo three times. It shows as uploaded but the old photo still appears everywhere.',
    customerName: 'Gary Jackson',
    customerEmail: 'gary.jackson@example.com',
    status: TicketStatus.OPEN,
    category: null,
    createdAt: daysAgo(9),
  },

  // NULL CATEGORY — RESOLVED
  {
    subject: 'Automated reports not arriving on schedule',
    body: 'Our weekly summary report is configured for Monday 8am but hasn\'t arrived for the past two weeks.',
    customerName: 'Holly Knight',
    customerEmail: 'holly.knight@example.com',
    status: TicketStatus.RESOLVED,
    category: null,
    createdAt: daysAgo(13),
  },
  {
    subject: 'Cannot update company logo',
    body: 'The company logo upload accepts the file and shows a preview, then shows an error when I click confirm.',
    customerName: 'Ian Lambert',
    customerEmail: 'ian.lambert@example.com',
    status: TicketStatus.RESOLVED,
    category: null,
    createdAt: daysAgo(17),
  },
  {
    subject: 'Notifications going to the wrong email',
    body: 'System notifications are being sent to a former employee\'s email even though I\'ve updated the notification settings.',
    customerName: 'Janet Mason',
    customerEmail: 'janet.mason@example.com',
    status: TicketStatus.RESOLVED,
    category: null,
    createdAt: daysAgo(21),
  },
  {
    subject: 'Sorting by name not working correctly',
    body: 'When I sort the customer list by last name, names starting with lowercase letters appear before uppercase ones.',
    customerName: 'Keith Nelson',
    customerEmail: 'keith.nelson@example.com',
    status: TicketStatus.RESOLVED,
    category: null,
    createdAt: daysAgo(27),
  },
  {
    subject: 'Page freezes when scrolling large data sets',
    body: 'The browser tab freezes for 10–15 seconds when I scroll through a list with more than 500 records.',
    customerName: 'Lisa Owen',
    customerEmail: 'lisa.owen@example.com',
    status: TicketStatus.RESOLVED,
    category: null,
    createdAt: daysAgo(33),
  },

  // NULL CATEGORY — CLOSED
  {
    subject: 'Old pricing shown on checkout page',
    body: 'Your pricing page shows $29/month but the checkout page charges $39/month. Which is correct?',
    customerName: 'Mark Peterson',
    customerEmail: 'mark.peterson@example.com',
    status: TicketStatus.CLOSED,
    category: null,
    createdAt: daysAgo(43),
  },
  {
    subject: 'Account merge request for two organisations',
    body: 'We acquired another company that also uses your platform. Can you merge the two accounts and retain all data?',
    customerName: 'Nina Quinn',
    customerEmail: 'nina.quinn@example.com',
    status: TicketStatus.CLOSED,
    category: null,
    createdAt: daysAgo(58),
  },
  {
    subject: 'Cannot export data in JSON format',
    body: 'The export options only show CSV and XML but the documentation mentions JSON export. Where is it?',
    customerName: 'Owen Roberts',
    customerEmail: 'owen.roberts@example.com',
    status: TicketStatus.CLOSED,
    category: null,
    createdAt: daysAgo(72),
  },
  {
    subject: 'Wrong currency shown after region change',
    body: 'I changed my account region from UK to US but prices still show in GBP everywhere except the checkout.',
    customerName: 'Priya Singh',
    customerEmail: 'priya.singh@example.com',
    status: TicketStatus.CLOSED,
    category: null,
    createdAt: daysAgo(88),
  },
  {
    subject: 'Cannot reopen a closed ticket in the portal',
    body: 'My issue was marked as closed but it hasn\'t been fully resolved. The portal doesn\'t give me an option to reopen it.',
    customerName: 'Raj Sharma',
    customerEmail: 'raj.sharma@example.com',
    status: TicketStatus.CLOSED,
    category: null,
    createdAt: daysAgo(95),
  },

  // More OPEN tickets to reach 100 with variety
  {
    subject: 'Upgrade from Starter to Business failing',
    body: 'Every time I try to upgrade my plan, the payment step errors out with "transaction declined" even though my card works elsewhere.',
    customerName: 'Sarah Thompson',
    customerEmail: 'sarah.thompson@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(1),
  },
  {
    subject: 'Multi-currency support question',
    body: 'We invoice clients in EUR, GBP and USD. Does your platform support multi-currency invoices on a single account?',
    customerName: 'Tom Underwood',
    customerEmail: 'tom.underwood@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.GENERAL_QUESTION,
    createdAt: daysAgo(2),
  },
  {
    subject: 'Data export format not compatible with QuickBooks',
    body: 'The exported CSV does not import correctly into QuickBooks Online. Column headers seem to differ from what QB expects.',
    customerName: 'Uma Vance',
    customerEmail: 'uma.vance@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(3),
  },
  {
    subject: 'Refund not received after 10 business days',
    body: 'I was told my refund would arrive within 5–10 business days. It has been 14 days and nothing has appeared.',
    customerName: 'Victor Walsh',
    customerEmail: 'victor.walsh@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.REFUND_REQUEST,
    createdAt: daysAgo(14),
  },
  {
    subject: 'Cannot set up recurring invoices',
    body: 'The recurring invoice feature appears in the settings but the toggle is greyed out. I\'m on the Business plan.',
    customerName: 'Wilma Xavier',
    customerEmail: 'wilma.xavier@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(4),
  },
  {
    subject: 'Request for extended trial',
    body: 'Our procurement process takes 30 days. The 14-day trial isn\'t enough for us to get approval. Can you extend it?',
    customerName: 'Xavier Young',
    customerEmail: 'xavier.young@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.GENERAL_QUESTION,
    createdAt: daysAgo(5),
  },
  {
    subject: 'Offline mode not syncing when reconnected',
    body: 'Changes made in offline mode are not syncing to the server after reconnecting. Data is being lost.',
    customerName: 'Yvonne Zhang',
    customerEmail: 'yvonne.zhang@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(6),
  },
  {
    subject: 'Partial refund for downgrade not processed',
    body: 'I downgraded from Business to Starter last week and was promised a prorated credit. My balance still shows zero.',
    customerName: 'Zachary Adams',
    customerEmail: 'zachary.adams@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.REFUND_REQUEST,
    createdAt: daysAgo(7),
  },
  {
    subject: 'White-label domain not propagating',
    body: 'I added white-label domain settings 72 hours ago but my clients still see your default domain.',
    customerName: 'Amy Bell',
    customerEmail: 'amy.bell@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(3),
  },
  {
    subject: 'Can I use your API without a paid plan?',
    body: 'I want to prototype an integration using your REST API. Is there an API sandbox available on the free tier?',
    customerName: 'Bruce Campbell',
    customerEmail: 'bruce.campbell@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.GENERAL_QUESTION,
    createdAt: daysAgo(1),
  },
  {
    subject: 'Notification emails going to spam',
    body: 'Several of our team members report that notification emails are landing in spam. Can you check your SPF and DKIM records?',
    customerName: 'Claire Davies',
    customerEmail: 'claire.davies@example.com',
    status: TicketStatus.RESOLVED,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(11),
  },
  {
    subject: 'Accidental account deletion — need restore',
    body: 'A junior admin accidentally deleted our main workspace. Is there a way to restore it? We have critical data in there.',
    customerName: 'Derek Evans',
    customerEmail: 'derek.evans@example.com',
    status: TicketStatus.RESOLVED,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(19),
  },
  {
    subject: 'Requesting refund due to competitor switch',
    body: 'We\'ve decided to move to a competitor. We paid annually and would like a prorated refund for the remaining 8 months.',
    customerName: 'Elaine Ford',
    customerEmail: 'elaine.ford@example.com',
    status: TicketStatus.RESOLVED,
    category: TicketCategory.REFUND_REQUEST,
    createdAt: daysAgo(26),
  },
  {
    subject: 'Widget embed code not displaying on site',
    body: 'I copied the embed code and placed it in my Webflow site but the widget never appears. I\'ve disabled ad blockers.',
    customerName: 'Felix Grant',
    customerEmail: 'felix.grant@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(2),
  },
  {
    subject: 'How to set up IP whitelisting?',
    body: 'Our security policy requires IP whitelisting for admin access. I can\'t find this option in the security settings.',
    customerName: 'Grace Howard',
    customerEmail: 'grace.howard@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.GENERAL_QUESTION,
    createdAt: daysAgo(3),
  },
  {
    subject: 'Stripe integration showing webhook errors',
    body: 'Our Stripe dashboard shows repeated webhook failures from your platform since yesterday at 3pm UTC.',
    customerName: 'Harry Ingram',
    customerEmail: 'harry.ingram@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(1),
  },
  {
    subject: 'Annual plan renews at old price?',
    body: 'My annual plan is up for renewal next month. Your pricing went up in September — will my renewal use the old or new rate?',
    customerName: 'Isabella Jones',
    customerEmail: 'isabella.jones@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.GENERAL_QUESTION,
    createdAt: daysAgo(4),
  },
  {
    subject: 'Duplicate invoices sent to client',
    body: 'The same invoice was sent to my client three times. They are unhappy. Please disable the retry logic.',
    customerName: 'Jake Kennedy',
    customerEmail: 'jake.kennedy@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(0),
  },
  {
    subject: 'Google Calendar sync stops after a few days',
    body: 'Calendar sync with Google works initially but stops after 3–4 days and requires manual reconnection every time.',
    customerName: 'Karen Lawrence',
    customerEmail: 'karen.lawrence@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(5),
  },
  {
    subject: 'Need to change invoice currency to EUR',
    body: 'All our clients are in Europe. How do I change the default invoice currency from USD to EUR?',
    customerName: 'Leonard Murphy',
    customerEmail: 'leonard.murphy@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.GENERAL_QUESTION,
    createdAt: daysAgo(2),
  },
  {
    subject: 'Refund for unused seats after team restructure',
    body: 'Following a company restructure we went from 50 to 30 users. Can we get a refund for the 20 unused seats?',
    customerName: 'Margaret Nash',
    customerEmail: 'margaret.nash@example.com',
    status: TicketStatus.CLOSED,
    category: TicketCategory.REFUND_REQUEST,
    createdAt: daysAgo(62),
  },
  {
    subject: 'API documentation link returns 404',
    body: 'The link to the REST API docs from your help centre returns a 404. I need the endpoint reference urgently.',
    customerName: 'Nathan Oliver',
    customerEmail: 'nathan.oliver@example.com',
    status: TicketStatus.RESOLVED,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(9),
  },
  {
    subject: 'Unable to close ticket from customer portal',
    body: 'The "Mark as resolved" button in the customer portal does nothing when clicked. I\'ve tried Chrome and Safari.',
    customerName: 'Olivia Palmer',
    customerEmail: 'olivia.palmer@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(6),
  },
  {
    subject: 'Requesting invoice in local currency (BRL)',
    body: 'Our Brazilian subsidiary needs invoices in BRL for tax purposes. Is this something you can accommodate?',
    customerName: 'Pedro Quiroga',
    customerEmail: 'pedro.quiroga@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.GENERAL_QUESTION,
    createdAt: daysAgo(3),
  },
  {
    subject: 'Account locked after too many login attempts',
    body: 'A team member got locked out after forgetting their password. The account unlock email isn\'t arriving.',
    customerName: 'Quinn Riley',
    customerEmail: 'quinn.riley@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(1),
  },
  {
    subject: 'Discount code not applying at checkout',
    body: 'I have a 20% discount code from your Black Friday campaign but the checkout page says the code is invalid.',
    customerName: 'Rebecca Stone',
    customerEmail: 'rebecca.stone@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.GENERAL_QUESTION,
    createdAt: daysAgo(2),
  },
  {
    subject: 'Database connection dropping under load',
    body: 'When more than 50 concurrent users are active, the app throws "connection pool exhausted" errors.',
    customerName: 'Simon Turner',
    customerEmail: 'simon.turner@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(3),
  },
  {
    subject: 'Refund for event ticket after cancellation',
    body: 'The online event I purchased a ticket for was cancelled without notice. I have not received my refund.',
    customerName: 'Tamara Underhill',
    customerEmail: 'tamara.underhill@example.com',
    status: TicketStatus.RESOLVED,
    category: TicketCategory.REFUND_REQUEST,
    createdAt: daysAgo(38),
  },
  {
    subject: 'How do I set up SAML-based SSO?',
    body: 'We use Azure AD for identity management. Do you support SAML 2.0 and is there a setup guide I can follow?',
    customerName: 'Ursula Vickers',
    customerEmail: 'ursula.vickers@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.GENERAL_QUESTION,
    createdAt: daysAgo(1),
  },
  {
    subject: 'Batch delete not working for archived records',
    body: 'Selecting all archived records and clicking "Delete selected" does nothing. No error, no confirmation, nothing happens.',
    customerName: 'Vincent Webb',
    customerEmail: 'vincent.webb@example.com',
    status: TicketStatus.CLOSED,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(77),
  },
  {
    subject: 'Slack integration not posting notifications',
    body: 'We connected Slack via OAuth but no notifications are posting to our #support channel despite events being triggered.',
    customerName: 'Wendy Xu',
    customerEmail: 'wendy.xu@example.com',
    status: TicketStatus.OPEN,
    category: TicketCategory.TECHNICAL_QUESTION,
    createdAt: daysAgo(2),
  },
];

async function main() {
  const count = await prisma.ticket.count();
  if (count > 0) {
    console.log(`Skipping — ${count} tickets already exist. Delete them first if you want to re-seed.`);
    return;
  }

  await prisma.ticket.createMany({ data: tickets });
  console.log(`Created ${tickets.length} tickets.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
